### ISSUE TITLE
Unnamed instances lead to ridiculously long instance names in the docs

### ISSUE THREAD

**Issue by adri326** [leanprover-community/mathlib4#8521] opened 2023-11-19 23:26 UTC
I think the following gems that can currently be found in the mathlib documentations speak for themselves.
(I apologize for anyone not using a markdown reader or viewing this on mobile)

- ["That's a mouthful!"](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/LocallyConvex/StrongTopology.html#ContinuousLinearMap.instLocallyConvexSpaceContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToSemiringToDivisionSemiringToSemifieldToFieldToAddCommMonoidToAddCommMonoidAddCommMonoidToContinuousAddToAddGroupModuleToSemiringTopologicalSpace)
- ["Why do I hear boss music?"](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Geometry/Manifold/Instances/Sphere.html#instLieGroupRealToNontriviallyNormedFieldDenselyNormedFieldEuclideanSpaceIsROrCFinOfNatNatInstOfNatNatFintypeToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedAddCommGroupNormedAddCommGroupENNRealInstOfNatToNatCastInstCanonicallyOrderedCommSemiringENNRealProof_1Fact_one_le_two_ennrealNormedAddCommGroupNormedSpaceToNormedFieldToNormedSpaceInnerProductSpaceModelWithCornersSelfSubtypeComplexMemSubmonoidToMulOneClassToMulZeroOneClassToNonAssocSemiringInstSemiringComplexInstMembershipInstSetLikeSubmonoidCircleToGroupCommGroupInstTopologicalSpaceSubtypeToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingInstNormedFieldComplexInstChartedSpaceEuclideanSpaceRealIsROrCFinOfNatNatInstOfNatNatFintypeToTopologicalSpaceUniformSpaceENNRealInstOfNatToNatCastInstCanonicallyOrderedCommSemiringENNRealProof_1ToUniformSpacePseudoMetricSpaceSubtypeComplexMemSubmonoidToMulOneClassToMulZeroOneClassToNonAssocSemiringInstSemiringComplexInstMembershipInstSetLikeSubmonoidCircleInstTopologicalSpaceSubtypeToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingInstNormedFieldComplex)
- ["Oh no..."](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/NormedSpace/OperatorNorm.html#ContinuousLinearMap.instNormedSpaceContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToNormedFieldIdToNonAssocSemiringContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupModuleSmulCommClass_selfToCommMonoidToCommRingToEuclideanDomainToMulActionToMonoidWithZeroToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingToSMulToZeroToAddMonoidToSMulZeroClassToZeroToSMulWithZeroContinuousSMulToZeroToCommMonoidWithZeroToCommGroupWithZeroBoundedSMulModuleSmulCommClass_selfToMulActionToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToSMulToZeroToAddMonoidToSMulZeroClassToSMulWithZeroContinuousSMulBoundedSMulInstSeminormedAddCommGroupContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToNormedFieldIdToNonAssocSemiringContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupModuleSmulCommClass_selfToCommMonoidToCommRingToEuclideanDomainToMulActionToMonoidWithZeroToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingToSMulToZeroToAddMonoidToSMulZeroClassToZeroToSMulWithZeroContinuousSMulToZeroToCommMonoidWithZeroToCommGroupWithZeroBoundedSMulModuleSmulCommClass_selfToMulActionToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToSMulToZeroToAddMonoidToSMulZeroClassToSMulWithZeroContinuousSMulBoundedSMul)

What seems to have happened is that Lean gave the `instance` a default name based on the classes referred to in the instance, and when those become complex, the default name grows out of proportion (with taller chains of class inheritance yielding worse results).

I don't know of an easier way to fix this other than painstakingly giving names to instances present in mathlib. The main inconvenience of these long instance names is that they tend to clutter the search result when no results are found.

**Comment by digama0** [comment] 2023-11-19 23:53
Duplicate of https://github.com/leanprover/lean4/issues/2343

**Closed by digama0** 2023-11-19 23:53 UTC
