### ISSUE TITLE
simp? not preserving <-

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover-community/mathlib4#7600] opened 2023-10-10 02:09 UTC
I was trying to fix a nonterminal simp that looked like
```
simp? [← mul_inv_rev, ← pow_bit0]
```
By adding in the question mark. But I got
```
Try this: simp only [zpow_negSucc, mul_inv_rev, pow_bit0]
```
Which is wrong.

**Comment by digama0** [comment] 2023-10-10 02:17
duplicate of https://github.com/leanprover/lean4/issues/2131

**Closed by digama0** 2023-10-10 02:17 UTC
Labels: bug
