### ISSUE TITLE
json: cannot unmarshal string into Go struct field lakeManifest.version of type int

### ISSUE THREAD

**Issue by futureflsl** [leanprover-community/mathlib4#14259] opened 2024-06-29 09:33 UTC
```
glean -lake-manifest-path lake-manifest.json error like:
glean -lake-manifest-path lake-manifest.json
2024/06/29 17:31:31 got dotElanBaseDir `C:\Users\admin\.elan`
2024/06/29 17:31:31 flag.Parse: got command = ``, version = ``
Found latest version: v0.1.12
run `glean -update` to update
panic: error parsing lake manifest `lake-manifest.json`, json: cannot unmarshal string into Go struct field lakeManifest.version of type int

goroutine 1 [running]:
github.com/alissa-tung/glean/glean.readAndParse({0xc000012168, 0x12})
        /Users/alissa/pod/glean/glean/lake.go:86 +0x1d4
github.com/alissa-tung/glean/glean.LakeSyncPackages()
        /Users/alissa/pod/glean/glean/lake.go:97 +0x30
main.main()
        /Users/alissa/pod/glean/main.go:25 +0x6f
```

**Comment by eric-wieser** [comment] 2024-08-01 20:24
Duplicate of #14222

**Closed by eric-wieser** 2024-08-01 20:24 UTC
