### ISSUE TITLE
obtain doesn't work with placeholders

### ISSUE THREAD

**Issue by Ruben-VandeVelde** [leanprover-community/mathlib4#5732] opened 2023-07-05 11:46 UTC
Example from #4707:

```lean
    obtain ⟨k, ⟨f⟩⟩ := IH ?_ s' ?_
```

doesn't work - no proof obligations are created for the placeholders (lean reports "no goals to be solved"), but omitting the proofs reports "don't know how to synthesize placeholder for argument 'h'".

```lean
    have := IH ?_ s' ?_
    obtain ⟨k, ⟨f⟩⟩ := this
```
works as expected.

**Comment by digama0** [comment] 2023-07-06 03:39
duplicate of leanprover/std4#116

**Closed by digama0** 2023-07-06 03:39 UTC
Labels: lean4-change-in-behaviour
