### ISSUE TITLE
There is no "delta" derive handler

### ISSUE THREAD

**Issue by joneugster** [leanprover-community/mathlib4#5020] opened 2023-06-13 21:06 UTC
In lean3 there was a default derive handler which would run `delta` on the goal. That is, it would pull the instance through the type synonym. We don't have this at present in lean4, so it is necessary to construct the instance by hand.

Examples:

```
deriving instance LargeCategory, ConcreteCategory for HeytAlgCat
```
turns into
```
deriving instance LargeCategory for HeytAlgCat

instance : ConcreteCategory HeytAlgCat := by
  dsimp [HeytAlgCat]
  infer_instance
```

**Comment by semorrison** [comment] 2023-06-15 02:32
This [link](https://github.com/search?q=repo%3Aleanprover-community%2Fmathlib4%20https%3A%2F%2Fgithub.com%2Fleanprover-community%2Fmathlib4%2Fissues%2F5020&type=code) searches for references to this issue in the source code.

**Comment by semorrison** [comment] 2023-06-17 00:09
See discussion on zulip: [1](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/inferInstance/near/250013184).

**Comment by Ruben-VandeVelde** [comment] 2023-06-17 06:03
Ref #380

**Comment by Komyyy** [comment] 2023-07-12 12:23
This issue is a duplicate of #380.

**Closed by Komyyy** 2023-07-12 12:23 UTC
Labels: lean4-change-in-behaviour
